import { HorizontalBox } from "std-widgets.slint";
import { Theme } from "../themes/material_dark.slint";

export component Titlebar inherits Rectangle {
    in-out property <string> title: "Printer";
    in-out property <string> time: "00:00 AM";
    in-out property <int> battery-percent: 100;
    in-out property <bool> show-battery: false;

    background: Theme.panel-bg;
    height: 50px;

    HorizontalLayout {
        padding: 10px;
        alignment: space-between;

        Text {
            text: root.title;
            font-size: 20px;
            color: Theme.text;
            vertical-alignment: center;
        }

        HorizontalLayout {
            spacing: 10px;
            alignment: end;

            if root.show-battery: Text {
                text: root.battery-percent + "%";
                color: Theme.text;
                vertical-alignment: center;
            }

            Text {
                text: root.time;
                color: Theme.text;
                vertical-alignment: center;
            }
        }
    }
}
