[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { version = "8.0.0", default-features = false }
heapless = "0.9.3"
micromath = "2.1.0"
hal = { path = "../hal" }
comms = { path = "../comms" }
embassy-time = { version = "0.5.1", features = ["defmt"] }
lexical-core = { version = "1.0.6", default-features = false }

[dev-dependencies]
approx = "0.5.1"
proptest = "1.11.0"
