[package]
name = "host-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-cors = "0.7.1"
actix-ws = "0.4.0"
tokio = { version = "1", features = ["full"] }
surrealdb = { version = "1.5.6", features = ["kv-rocksdb"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "2.0.20"
futures-util = "0.3"
tokio-serial = "5.4"
postcard = { version = "1.0", features = ["alloc"] }
cobs = "0.5.1"
lazy_static = "1.4"
env_logger = "0.11"
log = "0.4"
async-trait = "0.1"
mime = "0.3"
uuid = { version = "1.8", features = ["v4", "serde"] } # For file uploads
tokio-util = { version = "0.7", features = [
    "codec",
] } # For framed reads/writes on serial
bytes = "1"
chrono = { version = "0.4", features = ["serde"] } # For timestamps in models
dashmap = "6.2.1"
minijinja = { version = "2.24.0", features = ["loader", "json"] }
regex = "1.10"
actix-multipart = "0.8.1"
memmap2 = "0.9"
hostname = "0.4"
urlencoding = "2.1"
host-ui = { path = "../host-ui" } # Add host-ui as a dependency
