[package]
name = "r_klipp_motion"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = ["dep:tokio", "dep:nalgebra"]

[dependencies]
r_klipp_api = { path = "../r_klipp_api" }
heapless = "0.9.3"
micromath = "2.1.0"
tokio = { version = "1.53.1", features = ["full"], optional = true }
nalgebra = { version = "0.35.0", default-features = false, features = [
    "libm",
], optional = true }
