import { Button, VerticalBox } from "std-widgets.slint";

export component MainWindow inherits Window {
    VerticalBox {
        Text {
            text: "r_klipp Local UI";
            horizontal-alignment: center;
        }
        Text {
            id: connection_status;
            text: "Connection: PREDICTIVE MODE (Tier 1)";
            horizontal-alignment: center;
        }
        Button {
            text: "Files";
        }
        Button {
            text: "Settings";
        }
    }
}
