[package]
name = "control"
version = "0.1.0"
edition = "2024"

[dependencies]
micromath = "2.1.0"
heapless = "0.9.3"
embassy-executor = { version = "0.10.0", features = ["nightly"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt"] }

[dev-dependencies]
approx = "0.5.1"
