[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F407VGTx"

rustflags = [
    # Tell linker to use `memory.x`
    "-C", "link-arg=-Tlink.x",
    # Fix for some bare-metal targets
    "-C", "link-arg=--nmagic",
]
